<?php
/**
 * This file contains the correct buildings that are present in the sample data.
 */
return [
    "_ALL_",
    "ACAD+ACAD - Academiegebouw",
    "ARSENAAL+ARSENAAL - Arsenaal",
    "AVANBUEREN+AVANBUEREN - Leiden University College The Hague",
    "BROODFABR+BROODFABR - De Broodfabriek",
    "CDH-DIL+CDH-DIL - Theater Diligentia",
    "CDH-EXTERN+CDH-EXTERN - extern gebouw",
    "CDH-FOKKER+CDH-FOKKER - Fokker terminal",
    "CDH-HOUTZ+CDH-HOUTZ - De Houtzagerij",
    "CDH-KLOOST+CDH-KLOOST - Kloosterkerk",
    "CDH-KS+CDH-KS - Koninklijke Schouwburg",
    "CDH-LV+CDH-LV - Lange Voorhout",
    "CDH-NEWBAB+CDH-NEWBAB - New Babylon",
    "CDH-NWKERK+CDH-NWKERK - Nieuwe Kerk",
    "CDH-OPERA+CDH-OPERA - Zalencentrum Opera",
    "CDH-OPNUNI+CDH-OPNUNI - Open Universiteit",
    "CDH-SCHOUW+CDH-SCHOUW - Schouwburgstraat",
    "CDH-SH+CDH-SH - Stichthage",
    "CDH-TAHS+CDH-TAHS - Theater aan het Spui",
    "CDH-WLDFRM+CDH-WLDFRM - World Forum",
    "CDH-WYNHVN+CDH-WYNHVN - Wijnhaven",
    "CONSERV+CONSERV - Koninklijk Conservatorium",
    "EXTERN+EXTERN - ",
    "EYCKH1+EYCKH1 - Nederlandse Taal",
    "EYCKH2+EYCKH2 - Duits / Slavisch",
    "EYCKH3+EYCKH3 - Letteren",
    "EYCKH4+EYCKH4 - Engels",
    "GORL+GORL - Gorlaeus Laboratoria",
    "GRAV+GRAV - Gravensteen",
    "HHS+HHS - Haagse Hogeschool",
    "HOLIDAYINN+HOLIDAYINN - Holiday Inn Leiden",
    "HOOGLK+HOOGLK - Hooglandse Kerk",
    "HUIZINGA+HUIZINGA - Klassieke taal",
    "HUYGENS+HUYGENS - Huygens Lab.",
    "IJSHAL+IJSHAL - IJshal Menkenbaan",
    "KOG+KOG - Kamerlingh Onnes Gebouw",
    "LCP+LCP - Practicumgebouw",
    "LIPSIUS+LIPSIUS - Centraal Fac. gebouw",
    "LUMC-1+LUMC-1 - LUMC gebouw 1",
    "LUMC-2+LUMC-2 - LUMC gebouw 2",
    "LUMC-3+LUMC-3 - LUMC gebouw 3",
    "N.A+N.A - Not Applicable - Locatie nader te bepalen",
    "PATHOL+PATHOL - Pathologie",
    "PDLC+PDLC - Pieter de la Courtgebouw",
    "PJVETH+PJVETH - IIAS",
    "PKERK+PKERK - Pieterskerk",
    "RAP70+RAP70 - Rapenburg 70",
    "REG+REG - Theater De Regentes",
    "REUVENS+REUVENS - KITLV/Arch/Palestijnse oudheden",
    "SNELLIUS+SNELLIUS - Rekencentrum/Informatiseringsgroep",
    "STEEN+STEEN - van Steenis gebouw",
    "STERREW+STERREW - Sterrewacht",
    "STGEHZL+STGEHZL - Stads Gehoorzaal",
    "SYLVIUS+SYLVIUS - Sylvius lab",
    "UB+UB - Universiteits Bibliotheek",
    "UITHOF+UITHOF - ",
    "USC+USC - Universitair sportcentrum",
    "VRIESH1+VRIESH1 - Godgeleerdheid",
    "VRIESH2+VRIESH2 - Inst. Ned. Lexicologie",
    "VRIESH3+VRIESH3 - Midden Oosten Studies",
    "VRIESH4+VRIESH4 - CIF/NINO/Hebreeuws",
    "WIJKPL2+WIJKPL2 - Franse Taal- en Letterkunde",
    "WIJKPL3+WIJKPL3 - Spaans / Italiaans",
    "WIJKPL4+WIJKPL4 - Taalwetenschappen / Afrikaans",
];
