<?php
/**
 * This file contains the correct buildings that are present in the sample data.
 */
return [
    "_ALL_",
    "HUM-ARAB+Arabische taal en cultuur",
    "ARCH+Archeologie",
    "HUM-BB+Book and byte",
    "OUDE_UB+Bureau van de universiteit",
    "FWN-CML+Centrum voor milieuwetenschappen leiden",
    "HUM-CPA+Creative performing arts",
    "HUM-DUI+Duitse taal en cultuur",
    "HUM-DS+Dutch studies",
    "HUM-EGYP+Egyptische taal en cultuur",
    "HUM-ENG+Engelse taal en cultuur",
    "HUM-EUS+Europese unie studies",
    "999+Externe zalen (niet universitair)",
    "MED+Fac. geneeskunde afd. sz",
    "JUR+Faculteit der rechtsgeleerdheid ",
    "FWN+Faculteit wis- en natuurkunde",
    "FGGA+Faculty governance and global affairs",
    "FGGA-BSK+Fgga-bestuurskunde",
    "HUM-FPHS+Film and photographic studies",
    "HUM-FR+Franse taal en cultuur",
    "FSW+Fsw fac. der sociale wetenschappen ",
    "FSW-CWTS+Fsw-centre for science & techn. studies",
    "FSW-CANS+Fsw-cult antropologie/ ontw. sociologie",
    "FSW-LO+Fsw-iclon",
    "FSW-PEDA+Fsw-pedagogische wetenschappen",
    "FSW-POWE+Fsw-politieke wetenschap",
    "FSW-PSYC+Fsw-psychologie",
    "HUM-GS+Geschiedenis",
    "HUM-GODG+Godgeleerdheid",
    "GOR+Gorlaeus laboratorium",
    "HUM-GLTC+Grieks en latijnse taal en cultuur",
    "HUM-HATC+Hebreeuwse & armeense talen en culturen",
    "HUM-HJS+Hebreeuwse en joodse studies",
    "HUM-ALG+Hum-algemeen",
    "HUM-AZIE+Hum-azie",
    "HUM-MEDIA+Hum-media",
    "HUY+Huygens laboratorium",
    "FGGA-ISGA+Inst. of security of global affairs ",
    "FWN-IBL+Institute of biology leiden",
    "HUM-LUC+Instituut lucas",
    "HUM-MAN+Internationaal management en culltuur",
    "HUM-INT+Internationale studies",
    "HUM-ISL+Islamic studies",
    "HUM-ISLM+Islamologie",
    "HUM-ITAL+Italiaanse taal en cultuur",
    "HUM-JNM+Journalistiek en nieuwe media",
    "JURPAO+Juridisch post academisch onderwijs",
    "KOL+Kamerlingh onnes laboratorium",
    "HUM-KERN+Kerncurriculum letteren ",
    "HUM-KG+Kunstgeschiedenis",
    "HUM-LAS+Latijns-amerika studies",
    "HUM-LUCL+Leiden univ. centre for linguistics",
    "LUC+Leiden university college",
    "LAK+Leids academisch kunstcentrum",
    "HUM-CNWS+Letteren - cnws",
    "HUM-LITW+Literatuurwetenschap",
    "HUM-MO+Midden oosten",
    "HUM-NED+Nederlandse taal en cultuur",
    "HUM-NP+Nieuw-perzische taal en cultuur",
    "HUM-OCMW+Oude culturen van de mediterrane wereld",
    "HUM-PKST+Praktijkstudies",
    "HUM-SLAV+Slavische talen en culturen",
    "INF+Subfaculteit informatica",
    "WIS+Subfaculteit wiskunde",
    "SYL+Sylvius laboratorium",
    "HUM-TW+Taalwetenschap",
    "HUM-IN+Talen & culturen v. z.o. azie & oceanie",
    "HUM-TCMO+Talen & culturen van het midden oosten",
    "TC+Talen centrum",
    "HUM-TCMA+Talen en cult. v mesopotamie & anatolie",
    "HUM-AFRI+Talen en culturen van africa",
    "HUM-CHIN+Talen en culturen van china",
    "HUM-TCIA+Talen en culturen van indiaans amerika",
    "HUM-KOR+Tc korea",
    "HUM-JAP+Tc van japan",
    "HUM-ZCA+Tcit talen &  culturen v india en tibet",
    "HUM-TURK+Turkse taal en cultuur",
    "SDKOG+Ufb servicedesk kog",
    "BUR+Ufb/cluster binnenstad ",
    "UFB+Universitair facilitair bedrijf",
    "HUM-VIET+Vergelijk. indo-europese taalwet.schap",
    "HUM-VTW+Vergelijkende taalwetenschap",
    "HUM-WYSB+Wijsbegeerte",
    "WSD+Witte singel doelencomplex - alg dienst",
];
